{title: Znej haleluja Pánovi}

[Am]Znej hale[Em]luja Páno[Am]vi, znej hale[C]luja Páno[E]vi.
[Am]Znej hale[Em]luja, [F]znej hale[C]luja, [Am]znej hale[Em]luja Páno[Am]vi.

Ježiš je sveta Pán a Kráľ...
Ježiš so slávou príde k nám...
Spievajme Bohu nadšene...